apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-extracredit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Eszh/SWE645-HW3.git
    targetRevision: HEAD
    path: extracredit
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true